name: Update OpenAPI Documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/backend/src/**'
      - 'apps/backend/package.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-update-openapi:
    uses: ./.github/workflows/backend-update-openapi.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
